import type { Metadata } from "next";
import { Inter, Merriweather, Rokkitt } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./auth-provider";

// Define Inter for sans-serif text
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const rokkitt = Rokkitt({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Define Merriweather for serif or mono text
const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700"], // You can customize weights here
});

export const metadata: Metadata = {
  title: "Indivisual.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${merriweather.variable} ${rokkitt.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
